export const types = {
    //Sync
    AUTHENTICATE:       'AUTHENTICATE',
    INITIALIZE:         'INITIALIZE',
    LOGOUT:             'LOGOUT',
    //Async
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    LOGIN_ASYNC:        'LOGIN_ASYNC',
    SIGNUP_ASYNC:       'SIGNUP_ASYNC',
    INITIALIZE_ASYNC:   'INITIALIZE_ASYNC',
    LOGOUT_ASYNC:       'LOGOUT_ASYNC',
};
